version: '2'

services:
  templates:
    image: portainer/templates
    container_name: "portainer-templates"
    networks:
      - local

  portainer:
    image: portainer/portainer
    container_name: "portainer-app"
    command: --templates http://templates/templates.json
    networks:
      - local
    volumes:
     - /var/run/docker.sock:/var/run/docker.sock
      - /opt/portainer/data:/data

networks:
  local:
    driver: bridge
